DROP TABLE CLIENTINFO CASCADE CONSTRAINTS;

CREATE TABLE CLIENTINFO
(
  CLIENT_CODE    VARCHAR2(10),
  CLIENT_NAME    VARCHAR2(100),
  NO_LICENSE     NUMBER,
  REG_KEY        VARCHAR2(50),
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CLIENTINFO IS 'CLIENT INFORMATION';

/


