DROP TABLE EMPACCESSLOC CASCADE CONSTRAINTS;

CREATE TABLE EMPACCESSLOC
(
  EMPL_ID_NO     NUMBER,
  LOCATION_ID    NUMBER,
  CREATED_BY     VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  MODIFIED_BY    VARCHAR2(100 BYTE),
  DATE_MODIFIED  DATE
)
TABLESPACE HRIS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE EMPACCESSLOC IS 'EMPLOYEES ACCESS LOCATIONS';

/
